### ISSUE TITLE
Revisione Project Plan

### ISSUE THREAD

**Issue by LoreSchaeffer** [LoreSchaeffer/LupusInTabula-SoftEng#10]
Si richiede la revisione del project plan disponibile al percorso [docs/Project Plan.md](https://github.com/LoreSchaeffer/LupusInTabula-SoftEng/blob/main/docs/Project%20Plan.md)

**Comment by garganti** [comment]
molto bene il projectplan. Forse dovreste stabilire delle scadenze, cioè ok Agile/Xp però ogni tanto (tipo scrum) dovreste avere dei momenti in cui decidete cosa implementare e per quanto tempo. Buon lavoro.
