### ISSUE TITLE
Draft of the initial documentation for the project

### ISSUE THREAD

**Issue by LoreSchaeffer** [LoreSchaeffer/LupusInTabula-SoftEng#2]
- Project plan
- Introduction
- Process model
- Organization of the project
- Standards
- Guide lines and procedures
- Management activities
- Riscs
- Team members
- Resources
- Budget
- Timeline and deadlines

**Comment by MariRomelli** [comment]
I have completed the first part of the documentation. I temporarily left out budget and schedule for future releases.

[documentazione 1.0.docx](https://github.com/LoreSchaeffer/LupusInTabula-SoftEng/files/10019684/documentazione.1.0.docx)

**Comment by MariRomelli** [comment]
Carring out the documentation work. Carry out the part of configuration management and people management.

**Comment by MariRomelli** [comment]
Proceed with software life cycle and start software quality
